// Global constants
export const AppConstants = {
  // SERVER: 'localhost',
  SERVER: '192.168.99.100',
  CART_MICROSERVICE_PORT: '4444',
  PRODUCT_MICROSERVICE_PORT: '2222',
  ADD_TO_CART: 'ADD_TO_CART',
  GET_CART: 'GET_CART',
  GET_CART_RESPONSE: 'GET_CART_RESPONSE',
  ADD_TO_CART_RESPONSE: 'ADD_TO_CART_RESPONSE',
  GET_PRODUCT_RECOMMENDATIONS: 'GET_PRODUCT_RECOMMENDATIONS',
  GET_PRODUCT_RECOMMENDATIONS_RESPONSE: 'GET_PRODUCT_RECOMMENDATIONS_RESPONSE',
};